### PR TITLE
Remove duplicate paragraphs in README

### PR DESCRIPTION
**Pull request by CumpsD**
The Design Principles part is duplicated in the readme.

### CODE REVIEW

**Review by mxro — APPROVED** [review]
Thank you for your contribution. Looks good to me! Will update the template as well in a seperate PR.

**Comment by CumpsD** [comment]
Great project you got here by the way :) just discovered it today, great documentation

**Comment by mxro** [comment]
Thank you 😊 Any questions or suggestions you got, please don't hesitate to reach out. This is all still fairly new so happy for any feedback to refine things!

**Comment by CumpsD** [comment]
I can give you this feedback about `app-nextjs`, first impression:

image

I guess you are using linux only commands ;) `rm`

**Comment by CumpsD** [comment]
Another suggestion would be to have `yarn format-check` out of the box be valid:

image

**Comment by CumpsD** [comment]
Another feedback point, the docs about typescript mention pnpify but this is how the package looks:

image

I guess the docs are outdated

**Comment by mxro** [comment]
> I guess you are using linux only commands ;) rm

Oh that is very interesting! I am actually developing this on Windows, and I would have through that the Yarn portable shell would support `rm` https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell#yarnpkgshell

Just double checking you did a `yarn` and your `yarn --version` is `3.0.2`?

**Comment by CumpsD** [comment]
> > I guess you are using linux only commands ;) rm
> 
> Oh that is very interesting! I am actually developing this on Windows, and I would have through that the Yarn portable shell would support `rm` [https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell#yarnpkgshell](https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell?rgh-link-date=2022-02-23T20%3A45%3A52Z#yarnpkgshell)
> 
> Just double checking you did a `yarn` and your `yarn --version` is `3.0.2`?

correct, yarn is `3.0.2`, I did `yarn` and it's `yarn clean` that is giving the error

**Comment by mxro** [comment]
> Another suggestion would be to have yarn format-check out of the box be valid:

Yes, absolutely, created an issue for this: https://github.com/goldstack/goldstack/issues/107 - already solved it for `.pnp.cjs` but still not to figure out what is happening with the Yarn config.

**Comment by mxro** [comment]
Created issues for the other two things you have noticed as well: #109  and #110. Will try to get onto #109 first!

Thanks for the feedback, that's very helpful!

**Pull request merged**
